# Generated by Django 4.0 on 2021-12-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
