# Generated by Django 4.0 on 2021-12-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_api', '0002_alter_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.BooleanField(default=False),
        ),
    ]
