# Generated by Django 4.0 on 2021-12-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_api', '0003_remove_vehicle_driver_id_vehicle_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='with_drivers',
            field=models.CharField(default='no', max_length=20),
        ),
    ]
